apiVersion: apps/v1
kind: Deployment
metadata:
  # SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
  # SPDX-License-Identifier: Apache-2.0
  name: {{ include "webres6.fullname" . }}-api
  labels:
    {{- include "webres6.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicas | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "webres6.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.api.port | default 6400 }}"
        {{- end }}
      labels:
        {{- include "webres6.labels" . | nindent 8 }}
        {{- with .Values.api.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: webres6-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: webres6-api
          image: {{ .Values.api.image.repository | default "" .Values.image.repository }}{{ .Values.api.image.name | default "webres6-api" }}:{{ .Values.api.image.tag | default "latest" .Values.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: DEPLOYMENT
              value: {{ .Release.Name | quote }}
            {{- if .Values.seleniumHub.url }}
            - name: SELENIUM_REMOTE_URL
              value: {{ .Values.seleniumHub.url | quote }}
            {{- end }}
            {{- if .Values.seleniumHub.username }}
            - name: SELENIUM_USERNAME
              value: {{ .Values.seleniumHub.username | quote }}
            {{- end }}
            {{- if .Values.seleniumHub.password }}
            - name: SELENIUM_PASSWORD
              value: {{ .Values.seleniumHub.password | quote }}
            {{- end }}
            {{- if .Values.dnsprobe.url }}
            - name: DNSPROBE_API_URL
              value: {{ .Values.dnsprobe.url | quote }}
            {{- else if .Values.dnsprobe.enabled }}
            - name: DNSPROBE_API_URL
              value: "http://{{ include "webres6.fullname" . }}-dnsprobe:{{ .Values.dnsprobe.service.port }}/dnsprobe"
            {{- end }}
            {{- if .Values.api.redis.url }}
            - name: REDIS_URL
              value: {{ .Values.api.redis.url | quote }}
            {{- end }}
            - name: ENABLE_WHOIS
              value: {{ .Values.api.whois.enabled | quote | default "true" }}
            - name: WHOIS_CACHE_TTL
              value: {{ .Values.api.whois.cacheTTL | quote }}
            - name: RESULT_CACHE_TTL
              value: {{ .Values.api.results.cacheTTL | quote }}
            - name: RESULT_ARCHIVE_TTL
              value: {{ .Values.api.results.archiveTTL | quote }}
            - name: TIMEOUT
              value: {{ .Values.api.timeout | quote }}
            - name: PORT
              value: {{ .Values.api.port | quote }}
            - name: GUNICORN_CMD_ARGS
              value: "--threads {{ .Values.api.gunicornThreads }}"
            - name: ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name | default (include "webres6.fullname" .) }}
                  key: admin-key
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.api.port }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.api.port }}
          volumeMounts:
            - name: serverconfig
              mountPath: /app/serverconfig
              readOnly: true
          {{- with .Values.api.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: serverconfig
          configMap:
            name: {{ include "webres6.fullname" . }}-serverconfig
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
