apiVersion: v1
kind: ConfigMap
metadata:
  # SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
  # SPDX-License-Identifier: Apache-2.0
  name: {{ include "webres6.fullname" . }}-serverconfig
  labels:
    {{- include "webres6.labels" . | nindent 4 }}
data:
  PRIVACY: |
    {{- .Values.serverconfig.privacy | nindent 4 }}
  MESSAGE: |
    {{- .Values.serverconfig.message | nindent 4 }}
  {{- if .Values.serverconfig.webres6_extension_py }}
  webres6_extension.py: |
    {{- .Values.serverconfig.webres6_extension_py | nindent 4 }}
  {{- end }}
  {{- if .Values.serverconfig.url_blacklist }}
  url_blacklist.txt: |
    {{- range .Values.serverconfig.url_blacklist }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- end }}

