{{if .Values.dnsprobe.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  # SPDX-FileCopyrightText: 2025 SAP SE and IPv6 Web Resource Checker contributors
  # SPDX-License-Identifier: Apache-2.0
  name: {{ include "webres6.fullname" . }}-dnsprobe
  labels:
    {{- include "webres6.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dnsprobe.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "webres6.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dnsprobe.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "webres6.labels" . | nindent 8 }}
        {{- with .Values.dnsprobe.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: webres6-dnsprobe
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dnsprobe.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: webres6-dnsprobe
          image: {{ .Values.dnsprobe.image.repository | default "" .Values.image.repository }}{{ .Values.dnsprobe.image.name | default "webres6-dnsprobe" }}:{{ .Values.dnsprobe.image.tag | default "latest" .Values.image.tag }}
          imagePullPolicy: {{ .Values.dnsprobe.image.pullPolicy | default "IfNotPresent" }}
          env:
            - name: DEPLOYMENT
              value: {{ .Release.Name | quote }}
            - name: PORT
              value: {{ .Values.dnsprobe.port | quote }}
            {{- if .Values.dnsprobe.gunicornThreads }}
            - name: GUNICORN_CMD_ARGS
              value: "--threads {{ .Values.dnsprobe.gunicornThreads }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.dnsprobe.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.dnsprobe.port }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.dnsprobe.port }}
          {{- with .Values.dnsprobe.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dnsprobe.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
